In [1]:
import numpy as np

In [3]:
np.random.choice(3,2)

array([0, 1])

In [5]:
a = np.array([1,2,3,4,5]).reshape(-1,1)
a

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [9]:
a[:3,0]

array([1, 2, 3])

In [13]:
a = np.zeros((5,1))

In [14]:
a[0] = 2

In [15]:
a

array([[2.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [16]:
a == 0

array([[False],
       [ True],
       [ True],
       [ True],
       [ True]])